### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by seia-soto** [cozacomen/youtube-music-engine-embed#1]
Check the sources to keep going.

**Comment by ddarkr** [comment]
제가 보낸 PR 확인하시고, 적용하시면 됩니다.
https 에서 작동이 되지 않더군요

**Comment by HyungJu** [comment]
artwork-if, there is a EXTREMELY dangerous code.

this code downloads php file manager which can allow fuckin ivlis and nemo to download your 
source code.

DO NOT USE IT.
FUCKING BAD PLUGIN.

**Comment by HyungJu** [comment]
여기에 file_get_content 함수 지우세요.
